create table campaign_rule_state (
    campaign_id uuid primary key,
    rule_set_version_id varchar(64) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table campaign_rule_decision (
    id bigint generated by default as identity primary key,
    campaign_id uuid not null,
    decision_key varchar(64) not null,
    decision_order integer not null,
    status varchar(16) not null,
    current_resolution varchar(4000),
    configuration_value varchar(4000),
    reason varchar(4000),
    resolved_at timestamp null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_campaign_rule_decision_state
        foreign key (campaign_id) references campaign_rule_state (campaign_id) on delete cascade,
    constraint uq_campaign_rule_decision_key unique (campaign_id, decision_key)
);

create index idx_campaign_rule_decision_campaign_order
    on campaign_rule_decision (campaign_id, decision_order);
