alter table campaign_rule_decision
    add column actor varchar(255);

alter table campaign_rule_decision
    add column source varchar(255);

create table campaign_rule_audit_entry (
    id bigint generated by default as identity primary key,
    campaign_id uuid not null,
    rule_set_version_id varchar(64) not null,
    decision_key varchar(64) not null,
    decision_title varchar(255) not null,
    current_resolution varchar(4000) not null,
    configuration_value varchar(4000),
    reason varchar(4000) not null,
    actor varchar(255) not null,
    source varchar(255) not null,
    resolved_at timestamp not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_campaign_rule_audit_entry_state
        foreign key (campaign_id) references campaign_rule_state (campaign_id) on delete cascade
);

create index idx_campaign_rule_audit_entry_campaign_resolved_at
    on campaign_rule_audit_entry (campaign_id, resolved_at);
