create table campaign_audit_entry (
    id bigint generated by default as identity primary key,
    campaign_id uuid not null,
    rule_set_version_id varchar(64) not null,
    entry_type varchar(64) not null,
    subject_type varchar(64) not null,
    subject_id varchar(128),
    operation_type varchar(64) not null,
    title varchar(255) not null,
    current_resolution varchar(4000) not null,
    configuration_value varchar(4000),
    reason varchar(4000) not null,
    actor varchar(255) not null,
    source varchar(255) not null,
    occurred_at timestamp not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_campaign_audit_entry_state
        foreign key (campaign_id) references campaign_rule_state (campaign_id) on delete cascade
);

create index idx_campaign_audit_entry_campaign_occurred_at
    on campaign_audit_entry (campaign_id, occurred_at);
