package com.jadecaravan.domain.calculation;

public enum BusinessRuleCode {
    PASSENGER_CAPACITY_EXCEEDED,
    CARGO_CAPACITY_EXCEEDED,
    MISSING_DRIVER,
    CARGO_TYPE_NOT_ALLOWED,
    SPECIAL_CARGO_SUBTYPE_MISMATCH,
    SLAVE_CART_REQUIRES_SLAVES,
    PRISONER_CART_REQUIRES_PRISONERS,
    ZOO_CART_REJECTS_HUMANOIDS,
    GARDEN_CART_REQUIRES_HOUSED_FARMERS,
    SCHOOL_CART_TOO_MANY_TEACHERS,
    ORACLE_CART_REQUIRES_OPERATIONAL_CART,
    INSUFFICIENT_TOWING_STRENGTH,
    TOWING_FATIGUE_THRESHOLD_REACHED,
    PROVISIONS_SHORTAGE,
    MUTINY,
    REPAIR_REQUIRES_STATIONARY_DAY,
    REPAIR_REQUIRES_DRIVER,
    REPAIR_MATERIAL_REQUIRED,
    INVALID_FEAT_USAGE,
    UNKNOWN
}
